name: Deploy to Firebase

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install, build
      run: |
        yarn
        NODE_ENV=development yarn build
    - name: GitHub Action for Firebase
      uses: w9jds/firebase-action@v1.0.1
      env:
        PROJECT_ID: mod-helper
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      with:
        args: deploy --only hosting
